/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ACard: typeof import('ant-design-vue/es')['Card']
    ACol: typeof import('ant-design-vue/es')['Col']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    ARow: typeof import('ant-design-vue/es')['Row']
    ATypographyTitle: typeof import('ant-design-vue/es')['TypographyTitle']
    BaseButton: typeof import('./components/atoms/BaseButton.vue')['default']
    BaseInput: typeof import('./components/atoms/BaseInput.vue')['default']
    GradientButton: typeof import('./components/atoms/gradientButton.vue')['default']
    Header: typeof import('./components/organisms/Header.vue')['default']
    HomePage: typeof import('./components/pages/HomePage.vue')['default']
    LoginForm: typeof import('./components/molecules/LoginForm.vue')['default']
    LoginPage: typeof import('./components/pages/LoginPage.vue')['default']
    NavBar: typeof import('./components/organisms/NavBar.vue')['default']
    NavItem: typeof import('./components/atoms/NavItem.vue')['default']
    NavMenu: typeof import('./components/molecules/NavMenu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
